require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Override Firebase SDK Version
$FirebaseSDKVersion = '8.10.0'

platform :ios, '11.0'

target 'mobileMechanic' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

  target 'mobileMechanicTests' do
    inherit! :complete
    # Pods for testing
    pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end
end
